# Uncomment the next line to define a global platform for your project
platform :ios, '11.4'

target 'FortBuilder' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for FortBuilder
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'

  target 'FortBuilderTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FortBuilderUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
